Ek baat batao ...
Tum matlab bahut ajeeb h.M toh hu no doubt .sun agar kisi ladki koo bahut dm bhi aate hai vo bhi etna ajeeb ni karti kisi ke saat .
sab ke saat ache se baat karni chayiye agar time ni hota toh ye bolna hota h . aaj busy hu toh reply nhi kar matlab